Repository AY2223S2-CS2103T-T14-4/tp, pull requests merged in 2023-03, with the labels that each got.

#47 Update UserGuide.md
  docs/UserGuide.md
Labels: type.Task

#59 Update UserGuide.md
  docs/UserGuide.md
Labels: documentation

#73 Integrate assignment with model, commands, parser
  src/main/java/taa/assignment/Assignment.java
  src/main/java/taa/assignment/AssignmentList.java
  src/main/java/taa/logic/commands/AddAssignmentCommand.java
  src/main/java/taa/logic/commands/DeleteAssignmentCommand.java
  src/main/java/taa/logic/commands/GradeCommand.java
  src/main/java/taa/logic/parser/AddAssignmentCommandParser.java
  src/main/java/taa/logic/parser/DeleteAssignmentCommandParser.java
  src/main/java/taa/logic/parser/GradeCommandParser.java
  src/main/java/taa/model/Model.java
  src/main/java/taa/model/ModelManager.java
  src/test/java/taa/logic/commands/AddCommandTest.java
Labels: type.Task

#92 Add import command
  build.gradle
  docs/UserGuide.md
  src/main/java/taa/MainApp.java
  src/main/java/taa/commons/util/CsvUtil.java
  src/main/java/taa/commons/util/SampleDataUtil.java
  src/main/java/taa/logic/commands/ImportCommand.java
  src/main/java/taa/logic/parser/ImportCommandParser.java
  src/main/java/taa/logic/parser/TaaParser.java
  src/test/java/taa/testutil/PersonBuilder.java
Labels: type.Task

#98 Added Assignment Commands (add, delete, grade, list)
  src/main/java/taa/assignment/Assignment.java
  src/main/java/taa/assignment/AssignmentList.java
  src/main/java/taa/assignment/StudentList.java
  src/main/java/taa/assignment/Submission.java
  src/main/java/taa/logic/commands/AddAssignmentCommand.java
  src/main/java/taa/logic/commands/DeleteAssignmentCommand.java
  src/main/java/taa/logic/commands/GradeCommand.java
  src/main/java/taa/logic/commands/ListAssignmentCommand.java
  src/main/java/taa/logic/parser/AddAssignmentCommandParser.java
  src/main/java/taa/logic/parser/CliSyntax.java
  src/main/java/taa/logic/parser/DeleteAssignmentCommandParser.java
  src/main/java/taa/logic/parser/GradeCommandParser.java
  src/main/java/taa/logic/parser/TaaParser.java
  src/main/java/taa/model/Model.java
  src/main/java/taa/model/ModelManager.java
  src/test/java/taa/logic/commands/AddStudentCommandTest.java
Labels: type.Enhancement

#105 Update DeveloperGuide.md, draft
  docs/DeveloperGuide.md
Labels: documentation

#113 Feat/import flag
  docs/UserGuide.md
  src/main/java/taa/commons/util/StringUtil.java
  src/main/java/taa/logic/commands/ImportCommand.java
  src/main/java/taa/logic/parser/ImportCommandParser.java
  src/main/java/taa/model/student/Name.java
  src/main/java/taa/model/student/Student.java
  src/main/java/taa/model/student/UniqueStudentList.java
Labels: type.Task

#116 Add CSV file format and error handling to DG
  docs/DeveloperGuide.md
Labels: documentation

#117 Branch attendance participation
  docs/DeveloperGuide.md
  docs/diagrams/MarkAttendanceSequenceDiagram.puml
  docs/images/MarkAttendanceSequenceDiagram.png
Labels: documentation

#120 Assignment and grade improvements, bugfix, refactor, ui change
  src/main/java/taa/assignment/Assignment.java
  src/main/java/taa/assignment/AssignmentList.java
  src/main/java/taa/assignment/Submission.java
  src/main/java/taa/logic/commands/AddAssignmentCommand.java
  src/main/java/taa/logic/commands/GradeCommand.java
  src/main/java/taa/logic/parser/AddAssignmentCommandParser.java
  src/main/java/taa/logic/parser/CliSyntax.java
  src/main/java/taa/logic/parser/GradeCommandParser.java
  src/main/java/taa/model/Model.java
  src/main/java/taa/model/ModelManager.java
  src/test/java/taa/logic/commands/AddStudentCommandTest.java
Labels: enhancement

#124 Implements basic alarm function, allowing users to set alarms that will ring at specified timing
  docs/DeveloperGuide.md
  src/main/java/taa/logic/commands/AddAlarmCommand.java
  src/main/java/taa/logic/commands/ListCommand.java
  src/main/java/taa/logic/parser/AddAlarmCommandParser.java
  src/main/java/taa/logic/parser/CliSyntax.java
  src/main/java/taa/logic/parser/ParserUtil.java
  src/main/java/taa/logic/parser/TaaParser.java
  src/main/java/taa/model/Alarm.java
  src/main/java/taa/model/Model.java
  src/main/java/taa/model/ModelManager.java
  src/main/resources/sounds/bell.wav
  src/test/java/taa/logic/commands/AddStudentCommandTest.java
Labels: enhancement, type.Story, type.Task

#137 Complete Alarm Feature Without timer Countdown GUI
  src/main/java/taa/logic/commands/AddAlarmCommand.java
  src/main/java/taa/logic/commands/CommandResult.java
  src/main/java/taa/logic/commands/DeleteAlarmCommand.java
  src/main/java/taa/logic/commands/ExitCommand.java
  src/main/java/taa/logic/commands/HelpCommand.java
  src/main/java/taa/logic/commands/ListAlarmsCommand.java
  src/main/java/taa/logic/parser/AddAlarmCommandParser.java
  src/main/java/taa/logic/parser/DeleteAlarmCommandParser.java
  src/main/java/taa/logic/parser/TaaParser.java
  src/main/java/taa/model/Alarm.java
  src/main/java/taa/model/Model.java
  src/main/java/taa/model/ModelManager.java
  src/main/java/taa/model/alarm/Alarm.java
  src/main/java/taa/model/alarm/AlarmList.java
  src/main/resources/view/HelpWindow.css
  src/test/java/taa/logic/commands/AddStudentCommandTest.java
  src/test/java/taa/logic/commands/CommandResultTest.java
  src/test/java/taa/logic/commands/ExitCommandTest.java
  src/test/java/taa/logic/commands/HelpCommandTest.java
Labels: priority.High

#138 Update UG for alarm feature
  docs/UserGuide.md
Labels: documentation

#140 Update help command UI and include TAA commands
  src/main/java/taa/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: enhancement
