Repository AY2223S2-CS2103T-T14-4/tp, pull requests merged in 2023-04, with the labels that each got.

#196 Assignment bugfix
  src/main/java/taa/assignment/AssignmentList.java
  src/main/java/taa/assignment/Submission.java
  src/main/java/taa/logic/commands/DeleteAssignmentCommand.java
  src/main/java/taa/logic/commands/EditStudentCommand.java
  src/main/java/taa/logic/commands/UngradeCommand.java
  src/main/java/taa/logic/parser/AddAssignmentCommandParser.java
  src/main/java/taa/logic/parser/GradeCommandParser.java
  src/main/java/taa/logic/parser/ParserUtil.java
  src/main/java/taa/logic/parser/UngradeCommandParser.java
  src/main/java/taa/model/ModelManager.java
  src/main/java/taa/model/student/Student.java
  src/main/java/taa/model/student/Submissions.java
Labels: bug, enhancement, type.Epic

#197 Branch attendance participation
  docs/UserGuide.md
  src/main/java/taa/logic/parser/InsertParticipationParser.java
  src/main/java/taa/logic/parser/MarkAttendanceParser.java
  src/main/java/taa/logic/parser/ParserUtil.java
  src/main/java/taa/logic/parser/UnmarkAttendanceParser.java
  src/main/java/taa/model/student/Attendance.java
Labels: enhancement

#200 Add import image to UG
  docs/UserGuide.md
  docs/images/importResult.png
Labels: documentation

#211 Checked for submission string data errors + fix gui crashing
  src/main/java/taa/logic/commands/Command.java
  src/main/java/taa/model/Model.java
  src/main/java/taa/model/ModelManager.java
  src/main/java/taa/model/assignment/AssignmentList.java
  src/main/java/taa/model/assignment/Submission.java
  src/main/java/taa/model/assignment/exceptions/AssignmentException.java
  src/main/java/taa/model/assignment/exceptions/CorruptAssignmentStorageException.java
Labels: bug, enhancement

#223 Added Testcases for assignmentlist, assignment, storage
  src/main/java/taa/model/assignment/AssignmentList.java
  src/main/java/taa/model/assignment/Submission.java
  src/test/java/taa/model/assignment/AssignmentListTest.java
  src/test/java/taa/model/assignment/AssignmentTest.java
  src/test/java/taa/model/assignment/SubmissionTest.java
Labels: enhancement

#228 Documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteAssignmentSequenceDiagram.puml
  docs/diagrams/GradeSequenceDiagram.puml
  docs/diagrams/UngradeSequenceDiagram.puml
  docs/images/DeleteAssignmentSequenceDiagram.png
  docs/images/GradeSequenceDiagram.png
  docs/images/UngradeSequenceDiagram.png
  docs/index.md
  docs/team/tamkenghong.md
Labels: documentation

#229 Small bugfix for assignment json storage and gui format
  docs/UserGuide.md
  docs/images/AddAssignmentDemo.png
  docs/images/GradeDemo.png
  docs/images/ListAssignmentDemo.png
  src/main/java/taa/logic/commands/AddAssignmentCommand.java
  src/main/java/taa/model/assignment/Assignment.java
  src/main/java/taa/storage/JsonAdaptedAssignment.java
  src/main/java/taa/storage/JsonAdaptedStudent.java
  src/test/java/taa/model/assignment/AssignmentTest.java
Labels: bug, enhancement

#236 Updates design implementation for DG for alarms
  docs/DevOps.md
  docs/DeveloperGuide.md
Labels: documentation

#239 Update README.md
  README.md
Labels: enhancement
